<?xml version="1.0" ?>
<robot name="antrobot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- TODO: Colisions need to be updated to a simplified version -->
<!-- TODO: Inertial can be aproximated with cilinders if the sim is slow -->

<xacro:include filename="$(find antrobot_description)/urdf/materials.xacro" />
<xacro:include filename="$(find antrobot_description)/urdf/antrobot.trans" />
<xacro:include filename="$(find antrobot_description)/urdf/antrobot.gazebo" />

<!-- the robot wheel radius in meters -->
<xacro:property name="wheel_radius" value="0.03"/>
<!-- the robot wheel separation (wheel base) in meters -->
<xacro:property name="wheel_separation" value="0.219"/>

<!-- the robot wheel x, y, z offsets  in meters from base_link-->
<xacro:property name="wheel_x_offset" value="0.029613"/> 
<xacro:property name="wheel_y_offset" value="0.1095"/>
<xacro:property name="wheel_z_offset" value="0.005"/>

<!-- the robot rplidar x, y, z offsets  in meters from base_link-->
<xacro:property name="rplidar_x_offset" value="0.0"/> 
<xacro:property name="rplidar_y_offset" value="0.0"/>
<xacro:property name="rplidar_z_offset" value="0.186"/>

<!-- the robot rpicam x, y, z offsets  in meters from base_link-->
<xacro:property name="rpicam_x_offset" value="0.126235 "/> 
<xacro:property name="rpicam_y_offset" value="8.8e-05"/>
<xacro:property name="rpicam_z_offset" value="0.031943"/>

<!-- the robot realsense x, y, z offsets  in meters from base_link-->
<xacro:property name="realsense_x_offset" value="0.111521"/> 
<xacro:property name="realsense_y_offset" value="0.00012"/>
<xacro:property name="realsense_z_offset" value="0.132217"/>

<xacro:property name="pitch_offset" value="0 0.0523599"/>

<!-- Workaround for the KDL Tree -->
<!-- <link name="dummy"/>
<joint name="dummy_joint" type="fixed">
<parent link="dummy"/>
<child link="base_link"/>
</joint> -->

<link name='base_link'>
  <inertial>
    <origin xyz="-0.015797588649762044 0.0004259128735104659 0.06300813597085958" rpy="0 0 0"/>
    <mass value="1.5945437281135275"/>
    <inertia ixx="0.008584" iyy="0.010164" izz="0.010169" ixy="-6e-06" iyz="-3.3e-05" ixz="-0.0002"/>
  </inertial>
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://antrobot_description/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="light_grey"/>
  </visual>
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://antrobot_description/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="base_footprint"/>

<link name="wheel_left_link">
  <inertial>
    <origin xyz="-1.2728583304935648e-06 -0.0023063066184155906 6.00040961839729e-08" rpy="0 0 0"/>
    <mass value="0.010031169181516577"/>
    <inertia ixx="3e-06" iyy="6e-06" izz="3e-06" ixy="-0.0" iyz="-0.0" ixz="0.0"/>
  </inertial>
  <visual>
    <origin xyz="-${wheel_x_offset} -${wheel_y_offset} ${wheel_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://antrobot_description/meshes/wheel_left_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="blue"/>
  </visual>
  <collision>
    <origin xyz="-${wheel_x_offset} -${wheel_y_offset} ${wheel_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://antrobot_description/meshes/wheel_left_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="wheel_right_link">
  <inertial>
    <origin xyz="1.4357516585211672e-06 0.002306307129465418 6.000408169209298e-08" rpy="0 0 0"/>
    <mass value="0.010031169181516577"/>
    <inertia ixx="3e-06" iyy="6e-06" izz="3e-06" ixy="-0.0" iyz="0.0" ixz="-0.0"/>
  </inertial>
  <visual>
    <origin xyz="-${wheel_x_offset} ${wheel_y_offset} ${wheel_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://antrobot_description/meshes/wheel_right_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="blue"/>
  </visual>
  <collision>
    <origin xyz="-${wheel_x_offset} -${wheel_y_offset} ${wheel_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://antrobot_description/meshes/wheel_right_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="rplidar_link">
  <inertial>
    <origin xyz="0.0030931959904156093 -0.0003163045555262638 0.021005003394948152" rpy="0 0 0"/>
    <mass value="0.044595018191553856"/>
    <inertia ixx="2.5e-05" iyy="2.5e-05" izz="3.6e-05" ixy="0.0" iyz="0.0" ixz="-1e-06"/>
  </inertial>
  <visual>
    <origin xyz="-${rplidar_x_offset} -${rplidar_y_offset} -${rplidar_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://antrobot_description/meshes/rplidar_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="red"/>
  </visual>
  <collision>
    <origin xyz="-${rplidar_x_offset} -${rplidar_y_offset} -${rplidar_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://antrobot_description/meshes/rplidar_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="rpicam_link">
  <inertial>
    <origin xyz="-0.006587669853958977 5.666710231481823e-05 1.5965148283683672e-05" rpy="0 0 0"/>
    <mass value="0.0016269917920669669"/>
    <inertia ixx="0.0" iyy="0.0" izz="0.0" ixy="0.0" iyz="0.0" ixz="0.0"/>
  </inertial>
  <visual>
    <origin xyz="-${rpicam_x_offset} -${rpicam_y_offset} -${rpicam_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://antrobot_description/meshes/rpicam_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="yellow"/>
  </visual>
  <collision>
    <origin xyz="-${rpicam_x_offset} -${rpicam_y_offset} -${rpicam_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://antrobot_description/meshes/rpicam_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="realsense_link">
  <inertial>
    <origin xyz="-0.012605676757880976 0.001112839462886813 0.0006324082805583275" rpy="0 0 0"/>
    <mass value="0.04843109891123876"/>
    <inertia ixx="2.9e-05" iyy="4e-06" izz="3e-05" ixy="0.0" iyz="-0.0" ixz="0.0"/>
  </inertial>
  <visual>
    <origin xyz="-${realsense_x_offset} -${realsense_y_offset} -${realsense_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://antrobot_description/meshes/realsense_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="yellow"/>
  </visual>
  <collision>
    <origin xyz="-${realsense_x_offset} -${realsense_y_offset} -${realsense_z_offset}" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://antrobot_description/meshes/realsense_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<joint name="wheel_left_joint" type="continuous">
  <origin xyz="${wheel_x_offset} ${wheel_y_offset} -${wheel_z_offset}" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="wheel_left_link"/>
  <axis xyz="0.0 1.0 0.0"/>
</joint>

<joint name="wheel_right_joint" type="continuous">
  <origin xyz="${wheel_x_offset} -${wheel_y_offset} -${wheel_z_offset}" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="wheel_right_link"/>
  <axis xyz="0.0 1.0 0.0"/>
</joint>

<joint name="rplidar_joint" type="fixed">
  <origin xyz="${rplidar_x_offset} ${rplidar_y_offset} ${rplidar_z_offset}" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="rplidar_link"/>
</joint>

<joint name="rpicam_joint" type="fixed">
  <origin xyz="${rpicam_x_offset} ${rpicam_y_offset} ${rpicam_z_offset}" rpy="0 0 0.0523599 0"/>
  <parent link="base_link"/>
  <child link="rpicam_link"/>
</joint>

<joint name="realsense_joint" type="fixed">
  <origin xyz="${realsense_x_offset} ${realsense_y_offset} ${realsense_z_offset}" rpy="0 0.0523599 0"/>
  <parent link="base_link"/>
  <child link="realsense_link"/>
</joint>

<joint name="base_footprint_joint" type="fixed">
  <origin xyz="0 0 -${wheel_radius + wheel_z_offset}" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="base_footprint"/>
</joint>

</robot>
